pipeline {
  agent {
    kubernetes {
      yamlFile 'docker/pod.yaml'
    }
  }
  stages {
    stage('Docker build') {
      steps {
        container('dind') {
            sh '''
                docker pull hello-world
                docker tag hello-world container-registry-service.container-registry/hello-world:latest
                docker push container-registry-service.container-registry/hello-world:latest
            '''
        }
      }
    }
  }
}