pipeline {
  agent {
    kubernetes {
      yamlFile 'docker/pod.yaml'
    }
  }
  stages {
    stage('Docker build') {
      steps {
        container('dind') {
          sh 'docker run hello-world'
        }
      }
    }
  }
}