metadata:
  labels:
    app: jenkins
spec:
  containers:
    - name: jnlp
      env:
      - name: CONTAINER_ENV_VAR
        value: jnlp
    - name: dind
      image: docker:dind
      securityContext:
        privileged: true
      volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
  volumes:
    - name: dind-storage
      emptyDir: {}